In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv("sentiment_datasets/d1.csv")
df1

                                               Sentence Sentiment
0     The GeoSolutions technology will leverage Bene...  positive
1     $ESI on lows, down $1.50 to $2.50 BK a real po...  negative
2     For the last quarter of 2010 , Componenta 's n...  positive
3     According to the Finnish-Russian Chamber of Co...   neutral
4     The Swedish buyout firm has sold its remaining...   neutral
...                                                 ...       ...
5837  RISING costs have forced packaging producer Hu...  negative
5838  Nordic Walking was first used as a summer trai...   neutral
5839  According shipping company Viking Line , the E...   neutral
5840  In the building and home improvement trade , s...   neutral
5841  HELSINKI AFX - KCI Konecranes said it has won ...  positive

[5842 rows x 2 columns]

In [3]:
mapping = {
    "positive": 1,
    "neutral": 0,
    "negative": -1
}

df1["Sentiment"] = df1["Sentiment"].map(mapping)

df1.head()

                                            Sentence  Sentiment
0  The GeoSolutions technology will leverage Bene...          1
1  $ESI on lows, down $1.50 to $2.50 BK a real po...         -1
2  For the last quarter of 2010 , Componenta 's n...          1
3  According to the Finnish-Russian Chamber of Co...          0
4  The Swedish buyout firm has sold its remaining...          0

In [4]:
dfg1 = pd.read_csv("sentiment_datasets/goemotions_1.csv")
dfg1.head()

,text,id,author,subreddit,link_id,parent_id,created_utc,rater_id,example_very_unclear,admiration,...,love,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral
0,That game hurt.,eew5j0j,Brdd9,nrl,t3_ajis4z,t1_eew18eq,1.548381e+09,1,False,0,...,0,0,0,0,0,0,0,1,0,0
1,>sexuality shouldn’t be a grouping category I...,eemcysk,TheGreen888,unpopularopinion,t3_ai4q37,t3_ai4q37,1.548084e+09,37,True,0,...,0,0,0,0,0,0,0,0,0,0
2,"You do right, if you don't care then fuck 'em!",ed2mah1,Labalool,confessions,t3_abru74,t1_ed2m7g7,1.546428e+09,37,False,0,...,0,0,0,0,0,0,0,0,0,1
3,Man I love reddit.,eeibobj,MrsRobertshaw,facepalm,t3_ahulml,t3_ahulml,1.547965e+09,18,False,0,...,1,0,0,0,0,0,0,0,0,0
4,"[NAME] was nowhere near them, he was by the Fa...",eda6yn6,American_Fascist713,starwarsspeculation,t3_ackt2f,t1_eda65q2,1.546669e+09,2,False,0,...,0,0,0,0,0,0,0,0,0,1

In [5]:
dfg1.columns

Index(['text', 'id', 'author', 'subreddit', 'link_id', 'parent_id',
       'created_utc', 'rater_id', 'example_very_unclear', 'admiration',
       'amusement', 'anger', 'annoyance', 'approval', 'caring', 'confusion',
       'curiosity', 'desire', 'disappointment', 'disapproval', 'disgust',
       'embarrassment', 'excitement', 'fear', 'gratitude', 'grief', 'joy',
       'love', 'nervousness', 'optimism', 'pride', 'realization', 'relief',
       'remorse', 'sadness', 'surprise', 'neutral'],
      dtype='object')

In [6]:
positive_cols = [
'admiration','amusement','approval','caring','desire','excitement',
'gratitude','joy','love','optimism','pride','relief'
]

negative_cols = [
'anger','annoyance','disappointment','disapproval','disgust',
'embarrassment','fear','grief','nervousness','remorse','sadness'
]

neutral_cols = [
'neutral','confusion','curiosity','realization','surprise'
]

In [7]:
def get_sentiment(row):

    if row[positive_cols].sum() - row[negative_cols].sum() > 0:
        return 1

    if row[negative_cols].sum() - row[positive_cols].sum() > 0:
        return -1

    return 0

In [8]:
dfg1["sentiment"] = dfg1.apply(get_sentiment, axis=1)
dfg1 = dfg1[["text","sentiment"]]

In [9]:
dfg1

                                                    text  sentiment
0                                        That game hurt.         -1
1       >sexuality shouldn’t be a grouping category I...          0
2         You do right, if you don't care then fuck 'em!          0
3                                     Man I love reddit.          1
4      [NAME] was nowhere near them, he was by the Fa...          0
...                                                  ...        ...
69995        It's about fucking time, hope this is real.          0
69996  This is great! Can anyone make a request with ...          1
69997  I’m sorry. Can you please explain what are the...          0
69998                                No but it should be          0
69999  This is so cruel. I literally feel physically ...         -1

[70000 rows x 2 columns]

In [10]:
dfg2 = pd.read_csv("sentiment_datasets/goemotions_2.csv")
dfg2.columns

Index(['text', 'id', 'author', 'subreddit', 'link_id', 'parent_id',
       'created_utc', 'rater_id', 'example_very_unclear', 'admiration',
       'amusement', 'anger', 'annoyance', 'approval', 'caring', 'confusion',
       'curiosity', 'desire', 'disappointment', 'disapproval', 'disgust',
       'embarrassment', 'excitement', 'fear', 'gratitude', 'grief', 'joy',
       'love', 'nervousness', 'optimism', 'pride', 'realization', 'relief',
       'remorse', 'sadness', 'surprise', 'neutral'],
      dtype='object')

In [11]:
dfg2["sentiment"] = dfg2.apply(get_sentiment, axis=1)
dfg2 = dfg2[["text","sentiment"]]
dfg2

                                                    text  sentiment
0                                            We can hope          1
1                         Shhh don't give them the idea!         -1
2      Thank you so much, kind stranger. I really nee...          1
3      Ion know but it would be better for you to jus...          0
4      I'm honestly surprised. We should have fallen ...          1
...                                                  ...        ...
69995  I would cheer hard for a Cyborg win in that to...          1
69996    That's scalie, loli, and gmilf at the same time          0
69997  I have the worst memory ever. Idk if it's from...         -1
69998                                     So angry. PMS?         -1
69999  I mean, you can definitely beat someone up pas...          1

[70000 rows x 2 columns]

In [12]:
dfg3 = pd.read_csv("sentiment_datasets/goemotions_3.csv")
dfg3.columns

Index(['text', 'id', 'author', 'subreddit', 'link_id', 'parent_id',
       'created_utc', 'rater_id', 'example_very_unclear', 'admiration',
       'amusement', 'anger', 'annoyance', 'approval', 'caring', 'confusion',
       'curiosity', 'desire', 'disappointment', 'disapproval', 'disgust',
       'embarrassment', 'excitement', 'fear', 'gratitude', 'grief', 'joy',
       'love', 'nervousness', 'optimism', 'pride', 'realization', 'relief',
       'remorse', 'sadness', 'surprise', 'neutral'],
      dtype='object')

In [ ]:
dfg3["sentiment"] = dfg3.apply(get_sentiment, axis=1)
dfg3 = dfg3[["text","sentiment"]]
dfg3

In [ ]:
df1 = df1.rename(columns={"Sentence": "text","Sentiment": "sentiment"})

In [15]:
combined_df = pd.concat([df1, dfg1, dfg2, dfg3],ignore_index=True)
combined_df

                                                     text  sentiment
0       The GeoSolutions technology will leverage Bene...          1
1       $ESI on lows, down $1.50 to $2.50 BK a real po...         -1
2       For the last quarter of 2010 , Componenta 's n...          1
3       According to the Finnish-Russian Chamber of Co...          0
4       The Swedish buyout firm has sold its remaining...          0
...                                                   ...        ...
217062                             Everyone likes [NAME].          1
217063  Well when you’ve imported about a gazillion of...          1
217064                                 That looks amazing          1
217065  The FDA has plenty to criticize. But like here...         -1
217066  Desktop link: ^^/r/HelperBot_ ^^Downvote ^^to ...          0

[217067 rows x 2 columns]

In [16]:
combined_df["sentiment"].value_counts()

sentiment
 0    87381
 1    79375
-1    50311
Name: count, dtype: int64

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(max_features=50000,ngram_range=(1,2),stop_words="english",min_df=5)

In [18]:
x = combined_df["text"]
y = combined_df["sentiment"]

In [19]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=100,stratify=y)

In [20]:
x_train_vec = vectorizer.fit_transform(x_train)

In [21]:
x_test_vec = vectorizer.transform(x_test)

In [22]:
len(combined_df)

217067

## SVC used as first model

In [23]:
from sklearn.svm import LinearSVC
m1 = LinearSVC(class_weight="balanced")
m1.fit(x_train_vec, y_train)

LinearSVC(class_weight='balanced')

In [24]:
y_pred_1 = m1.predict(x_test_vec)

In [25]:
from sklearn.metrics import classification_report
classification_report(y_test, y_pred_1)

'              precision    recall  f1-score   support\n\n          -1       0.54      0.60      0.57     10062\n           0       0.62      0.59      0.60     17477\n           1       0.71      0.69      0.70     15875\n\n    accuracy                           0.63     43414\n   macro avg       0.62      0.63      0.62     43414\nweighted avg       0.63      0.63      0.63     43414\n'

## Logistic Regression used as second model

In [26]:
from sklearn.linear_model import LogisticRegression
m2 = LogisticRegression(max_iter=1000,class_weight="balanced")
m2.fit(x_train_vec, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [27]:
y_pred_2 = m2.predict(x_test_vec)

In [28]:
from sklearn.metrics import classification_report
classification_report(y_test, y_pred_2)

'              precision    recall  f1-score   support\n\n          -1       0.53      0.65      0.58     10062\n           0       0.63      0.58      0.60     17477\n           1       0.73      0.68      0.71     15875\n\n    accuracy                           0.63     43414\n   macro avg       0.63      0.64      0.63     43414\nweighted avg       0.64      0.63      0.63     43414\n'

# we will use Logistic Regression as best model

In [29]:
from sklearn.model_selection import GridSearchCV
param_grid = [
    {
        "solver": ["lbfgs"],
        "penalty": ["l2"],
        "C": [0.001, 0.01, 0.1, 1, 5, 10]
    },
    {
        "solver": ["saga"],
        "penalty": ["l1", "l2"],
        "C": [0.001, 0.01, 0.1, 1, 5, 10]
    }
]

In [30]:
grid = GridSearchCV(estimator=m2,param_grid=param_grid,cv=3,scoring="f1_macro",n_jobs=-1,verbose=2)

In [ ]:
grid.fit(x_train_vec, y_train)

Fitting 3 folds for each of 18 candidates, totalling 54 fits

In [ ]:
best_model = grid.best_estimator_

In [ ]:
y_pred_best = best_model.predict(x_test_vec)
classification_report(y_test, y_pred_best)

In [ ]:
import joblib
joblib.dump(best_model, "sentiment_analysis_model.joblib")
joblib.dump(vectorizer , "sentiment_vectorizer.joblib")